// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: district.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetAllDistricts
type GetAllDistrictsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   []*DistrictData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAllDistrictsResponse) Reset() {
	*x = GetAllDistrictsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllDistrictsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDistrictsResponse) ProtoMessage() {}

func (x *GetAllDistrictsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDistrictsResponse.ProtoReflect.Descriptor instead.
func (*GetAllDistrictsResponse) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllDistrictsResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetAllDistrictsResponse) GetData() []*DistrictData {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetDistrictByID
type GetDistrictByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *GetDistrictByIDInput `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *GetDistrictByIDRequest) Reset() {
	*x = GetDistrictByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDistrictByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistrictByIDRequest) ProtoMessage() {}

func (x *GetDistrictByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistrictByIDRequest.ProtoReflect.Descriptor instead.
func (*GetDistrictByIDRequest) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{1}
}

func (x *GetDistrictByIDRequest) GetRequest() *GetDistrictByIDInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type GetDistrictByIDInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDistrictByIDInput) Reset() {
	*x = GetDistrictByIDInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDistrictByIDInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistrictByIDInput) ProtoMessage() {}

func (x *GetDistrictByIDInput) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistrictByIDInput.ProtoReflect.Descriptor instead.
func (*GetDistrictByIDInput) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{2}
}

func (x *GetDistrictByIDInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDistrictByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   *DistrictData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetDistrictByIDResponse) Reset() {
	*x = GetDistrictByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDistrictByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistrictByIDResponse) ProtoMessage() {}

func (x *GetDistrictByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistrictByIDResponse.ProtoReflect.Descriptor instead.
func (*GetDistrictByIDResponse) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{3}
}

func (x *GetDistrictByIDResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetDistrictByIDResponse) GetData() *DistrictData {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetDistrictsByIDs
type GetDistrictsByIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *GetDistrictsByIDsInput `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *GetDistrictsByIDsRequest) Reset() {
	*x = GetDistrictsByIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDistrictsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistrictsByIDsRequest) ProtoMessage() {}

func (x *GetDistrictsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistrictsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetDistrictsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{4}
}

func (x *GetDistrictsByIDsRequest) GetRequest() *GetDistrictsByIDsInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type GetDistrictsByIDsInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDistrictsByIDsInput) Reset() {
	*x = GetDistrictsByIDsInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDistrictsByIDsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistrictsByIDsInput) ProtoMessage() {}

func (x *GetDistrictsByIDsInput) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistrictsByIDsInput.ProtoReflect.Descriptor instead.
func (*GetDistrictsByIDsInput) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{5}
}

func (x *GetDistrictsByIDsInput) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetDistrictsByIDsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   []*DistrictData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetDistrictsByIDsResponse) Reset() {
	*x = GetDistrictsByIDsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDistrictsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDistrictsByIDsResponse) ProtoMessage() {}

func (x *GetDistrictsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDistrictsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetDistrictsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{6}
}

func (x *GetDistrictsByIDsResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetDistrictsByIDsResponse) GetData() []*DistrictData {
	if x != nil {
		return x.Data
	}
	return nil
}

// InsertDistrict
type InsertDistrictRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *InsertDistrictInput `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *InsertDistrictRequest) Reset() {
	*x = InsertDistrictRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertDistrictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertDistrictRequest) ProtoMessage() {}

func (x *InsertDistrictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertDistrictRequest.ProtoReflect.Descriptor instead.
func (*InsertDistrictRequest) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{7}
}

func (x *InsertDistrictRequest) GetRequest() *InsertDistrictInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type InsertDistrictInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DistrictID   string `protobuf:"bytes,1,opt,name=districtID,proto3" json:"districtID,omitempty"`
	DistrictName string `protobuf:"bytes,2,opt,name=districtName,proto3" json:"districtName,omitempty"`
	CityID       string `protobuf:"bytes,3,opt,name=cityID,proto3" json:"cityID,omitempty"`
}

func (x *InsertDistrictInput) Reset() {
	*x = InsertDistrictInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertDistrictInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertDistrictInput) ProtoMessage() {}

func (x *InsertDistrictInput) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertDistrictInput.ProtoReflect.Descriptor instead.
func (*InsertDistrictInput) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{8}
}

func (x *InsertDistrictInput) GetDistrictID() string {
	if x != nil {
		return x.DistrictID
	}
	return ""
}

func (x *InsertDistrictInput) GetDistrictName() string {
	if x != nil {
		return x.DistrictName
	}
	return ""
}

func (x *InsertDistrictInput) GetCityID() string {
	if x != nil {
		return x.CityID
	}
	return ""
}

type InsertDistrictResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   *DistrictData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *InsertDistrictResponse) Reset() {
	*x = InsertDistrictResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertDistrictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertDistrictResponse) ProtoMessage() {}

func (x *InsertDistrictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertDistrictResponse.ProtoReflect.Descriptor instead.
func (*InsertDistrictResponse) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{9}
}

func (x *InsertDistrictResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *InsertDistrictResponse) GetData() *DistrictData {
	if x != nil {
		return x.Data
	}
	return nil
}

// InsertDistricts
type InsertDistrictsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request []*InsertDistrictInput `protobuf:"bytes,1,rep,name=request,proto3" json:"request,omitempty"`
}

func (x *InsertDistrictsRequest) Reset() {
	*x = InsertDistrictsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertDistrictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertDistrictsRequest) ProtoMessage() {}

func (x *InsertDistrictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertDistrictsRequest.ProtoReflect.Descriptor instead.
func (*InsertDistrictsRequest) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{10}
}

func (x *InsertDistrictsRequest) GetRequest() []*InsertDistrictInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type InsertDistrictsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   []*DistrictData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *InsertDistrictsResponse) Reset() {
	*x = InsertDistrictsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertDistrictsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertDistrictsResponse) ProtoMessage() {}

func (x *InsertDistrictsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertDistrictsResponse.ProtoReflect.Descriptor instead.
func (*InsertDistrictsResponse) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{11}
}

func (x *InsertDistrictsResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *InsertDistrictsResponse) GetData() []*DistrictData {
	if x != nil {
		return x.Data
	}
	return nil
}

// UpdateDistrict
type UpdateDistrictRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *UpdateDistrictInput `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *UpdateDistrictRequest) Reset() {
	*x = UpdateDistrictRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDistrictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDistrictRequest) ProtoMessage() {}

func (x *UpdateDistrictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDistrictRequest.ProtoReflect.Descriptor instead.
func (*UpdateDistrictRequest) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateDistrictRequest) GetRequest() *UpdateDistrictInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type UpdateDistrictInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DistrictID   string          `protobuf:"bytes,1,opt,name=districtID,proto3" json:"districtID,omitempty"`
	DistrictName *OptionalString `protobuf:"bytes,2,opt,name=districtName,proto3" json:"districtName,omitempty"`
	CityID       *OptionalString `protobuf:"bytes,3,opt,name=cityID,proto3" json:"cityID,omitempty"`
}

func (x *UpdateDistrictInput) Reset() {
	*x = UpdateDistrictInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDistrictInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDistrictInput) ProtoMessage() {}

func (x *UpdateDistrictInput) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDistrictInput.ProtoReflect.Descriptor instead.
func (*UpdateDistrictInput) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateDistrictInput) GetDistrictID() string {
	if x != nil {
		return x.DistrictID
	}
	return ""
}

func (x *UpdateDistrictInput) GetDistrictName() *OptionalString {
	if x != nil {
		return x.DistrictName
	}
	return nil
}

func (x *UpdateDistrictInput) GetCityID() *OptionalString {
	if x != nil {
		return x.CityID
	}
	return nil
}

type UpdateDistrictResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   *DistrictData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateDistrictResponse) Reset() {
	*x = UpdateDistrictResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDistrictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDistrictResponse) ProtoMessage() {}

func (x *UpdateDistrictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDistrictResponse.ProtoReflect.Descriptor instead.
func (*UpdateDistrictResponse) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateDistrictResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UpdateDistrictResponse) GetData() *DistrictData {
	if x != nil {
		return x.Data
	}
	return nil
}

// UpdateDistricts
type UpdateDistrictsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request []*UpdateDistrictInput `protobuf:"bytes,1,rep,name=request,proto3" json:"request,omitempty"`
}

func (x *UpdateDistrictsRequest) Reset() {
	*x = UpdateDistrictsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDistrictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDistrictsRequest) ProtoMessage() {}

func (x *UpdateDistrictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDistrictsRequest.ProtoReflect.Descriptor instead.
func (*UpdateDistrictsRequest) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateDistrictsRequest) GetRequest() []*UpdateDistrictInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type UpdateDistrictsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   []*DistrictData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateDistrictsResponse) Reset() {
	*x = UpdateDistrictsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDistrictsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDistrictsResponse) ProtoMessage() {}

func (x *UpdateDistrictsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDistrictsResponse.ProtoReflect.Descriptor instead.
func (*UpdateDistrictsResponse) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateDistrictsResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UpdateDistrictsResponse) GetData() []*DistrictData {
	if x != nil {
		return x.Data
	}
	return nil
}

// DeleteDistrict
type DeleteDistrictRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *DeleteDistrictInput `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *DeleteDistrictRequest) Reset() {
	*x = DeleteDistrictRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDistrictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDistrictRequest) ProtoMessage() {}

func (x *DeleteDistrictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDistrictRequest.ProtoReflect.Descriptor instead.
func (*DeleteDistrictRequest) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteDistrictRequest) GetRequest() *DeleteDistrictInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type DeleteDistrictInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDistrictInput) Reset() {
	*x = DeleteDistrictInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDistrictInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDistrictInput) ProtoMessage() {}

func (x *DeleteDistrictInput) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDistrictInput.ProtoReflect.Descriptor instead.
func (*DeleteDistrictInput) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteDistrictInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDistrictResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   *DistrictData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DeleteDistrictResponse) Reset() {
	*x = DeleteDistrictResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDistrictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDistrictResponse) ProtoMessage() {}

func (x *DeleteDistrictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDistrictResponse.ProtoReflect.Descriptor instead.
func (*DeleteDistrictResponse) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteDistrictResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeleteDistrictResponse) GetData() *DistrictData {
	if x != nil {
		return x.Data
	}
	return nil
}

// DeleteDistricts
type DeleteDistrictsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *DeleteDistrictsInput `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *DeleteDistrictsRequest) Reset() {
	*x = DeleteDistrictsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDistrictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDistrictsRequest) ProtoMessage() {}

func (x *DeleteDistrictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDistrictsRequest.ProtoReflect.Descriptor instead.
func (*DeleteDistrictsRequest) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteDistrictsRequest) GetRequest() *DeleteDistrictsInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type DeleteDistrictsInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDistrictsInput) Reset() {
	*x = DeleteDistrictsInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDistrictsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDistrictsInput) ProtoMessage() {}

func (x *DeleteDistrictsInput) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDistrictsInput.ProtoReflect.Descriptor instead.
func (*DeleteDistrictsInput) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteDistrictsInput) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeleteDistrictsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   []*DistrictData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *DeleteDistrictsResponse) Reset() {
	*x = DeleteDistrictsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDistrictsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDistrictsResponse) ProtoMessage() {}

func (x *DeleteDistrictsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDistrictsResponse.ProtoReflect.Descriptor instead.
func (*DeleteDistrictsResponse) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteDistrictsResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeleteDistrictsResponse) GetData() []*DistrictData {
	if x != nil {
		return x.Data
	}
	return nil
}

// Base Data
type DistrictData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DistrictID   string `protobuf:"bytes,1,opt,name=districtID,proto3" json:"districtID,omitempty"`
	DistrictName string `protobuf:"bytes,2,opt,name=districtName,proto3" json:"districtName,omitempty"`
	CityID       string `protobuf:"bytes,3,opt,name=cityID,proto3" json:"cityID,omitempty"`
}

func (x *DistrictData) Reset() {
	*x = DistrictData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistrictData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistrictData) ProtoMessage() {}

func (x *DistrictData) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistrictData.ProtoReflect.Descriptor instead.
func (*DistrictData) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{23}
}

func (x *DistrictData) GetDistrictID() string {
	if x != nil {
		return x.DistrictID
	}
	return ""
}

func (x *DistrictData) GetDistrictName() string {
	if x != nil {
		return x.DistrictName
	}
	return ""
}

func (x *DistrictData) GetCityID() string {
	if x != nil {
		return x.CityID
	}
	return ""
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message []string `protobuf:"bytes,2,rep,name=message,proto3" json:"message,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{24}
}

func (x *Header) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Header) GetMessage() []string {
	if x != nil {
		return x.Message
	}
	return nil
}

type OptionalString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	HasSet bool   `protobuf:"varint,2,opt,name=hasSet,proto3" json:"hasSet,omitempty"`
}

func (x *OptionalString) Reset() {
	*x = OptionalString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_district_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionalString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalString) ProtoMessage() {}

func (x *OptionalString) ProtoReflect() protoreflect.Message {
	mi := &file_district_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalString.ProtoReflect.Descriptor instead.
func (*OptionalString) Descriptor() ([]byte, []int) {
	return file_district_proto_rawDescGZIP(), []int{25}
}

func (x *OptionalString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OptionalString) GetHasSet() bool {
	if x != nil {
		return x.HasSet
	}
	return false
}

var File_district_proto protoreflect.FileDescriptor

var file_district_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x52, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x44,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x38, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x42, 0x79, 0x49, 0x44, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x42, 0x79, 0x49, 0x44, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x6f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x56, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3a, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x20, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x28, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x42, 0x79, 0x49,
	0x44, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x71, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x44, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2a,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x50, 0x0a, 0x15, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x71, 0x0a, 0x13,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x22,
	0x6e, 0x0a, 0x16, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x44, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x51, 0x0a, 0x16, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x6f, 0x0a, 0x17, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74,
	0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x50, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa5, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x49, 0x44, 0x12, 0x3c, 0x0a,
	0x0c, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x0c, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x63,
	0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x64, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x22, 0x6e, 0x0a,
	0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x51, 0x0a,
	0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x6f, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x44,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x50, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6e, 0x0a, 0x16, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2a,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x52, 0x0a, 0x16, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x26,
	0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74,
	0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6f, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6a, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x69, 0x74,
	0x79, 0x49, 0x44, 0x22, 0x3a, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x3e, 0x0a, 0x0e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x73, 0x53, 0x65,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x68, 0x61, 0x73, 0x53, 0x65, 0x74, 0x32,
	0xae, 0x06, 0x0a, 0x0f, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x21,
	0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x42, 0x79, 0x49, 0x44, 0x12, 0x20, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x42,
	0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x42, 0x79, 0x49,
	0x44, 0x73, 0x12, 0x22, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x42, 0x79,
	0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a,
	0x0e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x12,
	0x1f, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0f, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x44, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x12, 0x20, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x44, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55,
	0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74,
	0x12, 0x1f, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x12, 0x20, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x55, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63,
	0x74, 0x12, 0x1f, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x12, 0x20, 0x2e, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x64, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x03, 0x5a, 0x01, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_district_proto_rawDescOnce sync.Once
	file_district_proto_rawDescData = file_district_proto_rawDesc
)

func file_district_proto_rawDescGZIP() []byte {
	file_district_proto_rawDescOnce.Do(func() {
		file_district_proto_rawDescData = protoimpl.X.CompressGZIP(file_district_proto_rawDescData)
	})
	return file_district_proto_rawDescData
}

var file_district_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_district_proto_goTypes = []interface{}{
	(*GetAllDistrictsResponse)(nil),   // 0: district.GetAllDistrictsResponse
	(*GetDistrictByIDRequest)(nil),    // 1: district.GetDistrictByIDRequest
	(*GetDistrictByIDInput)(nil),      // 2: district.GetDistrictByIDInput
	(*GetDistrictByIDResponse)(nil),   // 3: district.GetDistrictByIDResponse
	(*GetDistrictsByIDsRequest)(nil),  // 4: district.GetDistrictsByIDsRequest
	(*GetDistrictsByIDsInput)(nil),    // 5: district.GetDistrictsByIDsInput
	(*GetDistrictsByIDsResponse)(nil), // 6: district.GetDistrictsByIDsResponse
	(*InsertDistrictRequest)(nil),     // 7: district.InsertDistrictRequest
	(*InsertDistrictInput)(nil),       // 8: district.InsertDistrictInput
	(*InsertDistrictResponse)(nil),    // 9: district.InsertDistrictResponse
	(*InsertDistrictsRequest)(nil),    // 10: district.InsertDistrictsRequest
	(*InsertDistrictsResponse)(nil),   // 11: district.InsertDistrictsResponse
	(*UpdateDistrictRequest)(nil),     // 12: district.UpdateDistrictRequest
	(*UpdateDistrictInput)(nil),       // 13: district.UpdateDistrictInput
	(*UpdateDistrictResponse)(nil),    // 14: district.UpdateDistrictResponse
	(*UpdateDistrictsRequest)(nil),    // 15: district.UpdateDistrictsRequest
	(*UpdateDistrictsResponse)(nil),   // 16: district.UpdateDistrictsResponse
	(*DeleteDistrictRequest)(nil),     // 17: district.DeleteDistrictRequest
	(*DeleteDistrictInput)(nil),       // 18: district.DeleteDistrictInput
	(*DeleteDistrictResponse)(nil),    // 19: district.DeleteDistrictResponse
	(*DeleteDistrictsRequest)(nil),    // 20: district.DeleteDistrictsRequest
	(*DeleteDistrictsInput)(nil),      // 21: district.DeleteDistrictsInput
	(*DeleteDistrictsResponse)(nil),   // 22: district.DeleteDistrictsResponse
	(*DistrictData)(nil),              // 23: district.DistrictData
	(*Header)(nil),                    // 24: district.Header
	(*OptionalString)(nil),            // 25: district.OptionalString
	(*emptypb.Empty)(nil),             // 26: google.protobuf.Empty
}
var file_district_proto_depIdxs = []int32{
	24, // 0: district.GetAllDistrictsResponse.header:type_name -> district.Header
	23, // 1: district.GetAllDistrictsResponse.data:type_name -> district.DistrictData
	2,  // 2: district.GetDistrictByIDRequest.request:type_name -> district.GetDistrictByIDInput
	24, // 3: district.GetDistrictByIDResponse.header:type_name -> district.Header
	23, // 4: district.GetDistrictByIDResponse.data:type_name -> district.DistrictData
	5,  // 5: district.GetDistrictsByIDsRequest.request:type_name -> district.GetDistrictsByIDsInput
	24, // 6: district.GetDistrictsByIDsResponse.header:type_name -> district.Header
	23, // 7: district.GetDistrictsByIDsResponse.data:type_name -> district.DistrictData
	8,  // 8: district.InsertDistrictRequest.request:type_name -> district.InsertDistrictInput
	24, // 9: district.InsertDistrictResponse.header:type_name -> district.Header
	23, // 10: district.InsertDistrictResponse.data:type_name -> district.DistrictData
	8,  // 11: district.InsertDistrictsRequest.request:type_name -> district.InsertDistrictInput
	24, // 12: district.InsertDistrictsResponse.header:type_name -> district.Header
	23, // 13: district.InsertDistrictsResponse.data:type_name -> district.DistrictData
	13, // 14: district.UpdateDistrictRequest.request:type_name -> district.UpdateDistrictInput
	25, // 15: district.UpdateDistrictInput.districtName:type_name -> district.OptionalString
	25, // 16: district.UpdateDistrictInput.cityID:type_name -> district.OptionalString
	24, // 17: district.UpdateDistrictResponse.header:type_name -> district.Header
	23, // 18: district.UpdateDistrictResponse.data:type_name -> district.DistrictData
	13, // 19: district.UpdateDistrictsRequest.request:type_name -> district.UpdateDistrictInput
	24, // 20: district.UpdateDistrictsResponse.header:type_name -> district.Header
	23, // 21: district.UpdateDistrictsResponse.data:type_name -> district.DistrictData
	18, // 22: district.DeleteDistrictRequest.request:type_name -> district.DeleteDistrictInput
	24, // 23: district.DeleteDistrictResponse.header:type_name -> district.Header
	23, // 24: district.DeleteDistrictResponse.data:type_name -> district.DistrictData
	21, // 25: district.DeleteDistrictsRequest.request:type_name -> district.DeleteDistrictsInput
	24, // 26: district.DeleteDistrictsResponse.header:type_name -> district.Header
	23, // 27: district.DeleteDistrictsResponse.data:type_name -> district.DistrictData
	26, // 28: district.DistrictService.GetAllDistricts:input_type -> google.protobuf.Empty
	1,  // 29: district.DistrictService.GetDistrictByID:input_type -> district.GetDistrictByIDRequest
	4,  // 30: district.DistrictService.GetDistrictsByIDs:input_type -> district.GetDistrictsByIDsRequest
	7,  // 31: district.DistrictService.InsertDistrict:input_type -> district.InsertDistrictRequest
	10, // 32: district.DistrictService.InsertDistricts:input_type -> district.InsertDistrictsRequest
	12, // 33: district.DistrictService.UpdateDistrict:input_type -> district.UpdateDistrictRequest
	15, // 34: district.DistrictService.UpdateDistricts:input_type -> district.UpdateDistrictsRequest
	17, // 35: district.DistrictService.DeleteDistrict:input_type -> district.DeleteDistrictRequest
	20, // 36: district.DistrictService.DeleteDistricts:input_type -> district.DeleteDistrictsRequest
	0,  // 37: district.DistrictService.GetAllDistricts:output_type -> district.GetAllDistrictsResponse
	3,  // 38: district.DistrictService.GetDistrictByID:output_type -> district.GetDistrictByIDResponse
	6,  // 39: district.DistrictService.GetDistrictsByIDs:output_type -> district.GetDistrictsByIDsResponse
	9,  // 40: district.DistrictService.InsertDistrict:output_type -> district.InsertDistrictResponse
	11, // 41: district.DistrictService.InsertDistricts:output_type -> district.InsertDistrictsResponse
	14, // 42: district.DistrictService.UpdateDistrict:output_type -> district.UpdateDistrictResponse
	16, // 43: district.DistrictService.UpdateDistricts:output_type -> district.UpdateDistrictsResponse
	19, // 44: district.DistrictService.DeleteDistrict:output_type -> district.DeleteDistrictResponse
	22, // 45: district.DistrictService.DeleteDistricts:output_type -> district.DeleteDistrictsResponse
	37, // [37:46] is the sub-list for method output_type
	28, // [28:37] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_district_proto_init() }
func file_district_proto_init() {
	if File_district_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_district_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllDistrictsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDistrictByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDistrictByIDInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDistrictByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDistrictsByIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDistrictsByIDsInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDistrictsByIDsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertDistrictRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertDistrictInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertDistrictResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertDistrictsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertDistrictsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDistrictRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDistrictInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDistrictResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDistrictsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDistrictsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDistrictRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDistrictInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDistrictResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDistrictsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDistrictsInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDistrictsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistrictData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_district_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionalString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_district_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_district_proto_goTypes,
		DependencyIndexes: file_district_proto_depIdxs,
		MessageInfos:      file_district_proto_msgTypes,
	}.Build()
	File_district_proto = out.File
	file_district_proto_rawDesc = nil
	file_district_proto_goTypes = nil
	file_district_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DistrictServiceClient is the client API for DistrictService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DistrictServiceClient interface {
	GetAllDistricts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllDistrictsResponse, error)
	GetDistrictByID(ctx context.Context, in *GetDistrictByIDRequest, opts ...grpc.CallOption) (*GetDistrictByIDResponse, error)
	GetDistrictsByIDs(ctx context.Context, in *GetDistrictsByIDsRequest, opts ...grpc.CallOption) (*GetDistrictsByIDsResponse, error)
	InsertDistrict(ctx context.Context, in *InsertDistrictRequest, opts ...grpc.CallOption) (*InsertDistrictResponse, error)
	InsertDistricts(ctx context.Context, in *InsertDistrictsRequest, opts ...grpc.CallOption) (*InsertDistrictsResponse, error)
	UpdateDistrict(ctx context.Context, in *UpdateDistrictRequest, opts ...grpc.CallOption) (*UpdateDistrictResponse, error)
	UpdateDistricts(ctx context.Context, in *UpdateDistrictsRequest, opts ...grpc.CallOption) (*UpdateDistrictsResponse, error)
	DeleteDistrict(ctx context.Context, in *DeleteDistrictRequest, opts ...grpc.CallOption) (*DeleteDistrictResponse, error)
	DeleteDistricts(ctx context.Context, in *DeleteDistrictsRequest, opts ...grpc.CallOption) (*DeleteDistrictsResponse, error)
}

type districtServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDistrictServiceClient(cc grpc.ClientConnInterface) DistrictServiceClient {
	return &districtServiceClient{cc}
}

func (c *districtServiceClient) GetAllDistricts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllDistrictsResponse, error) {
	out := new(GetAllDistrictsResponse)
	err := c.cc.Invoke(ctx, "/district.DistrictService/GetAllDistricts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *districtServiceClient) GetDistrictByID(ctx context.Context, in *GetDistrictByIDRequest, opts ...grpc.CallOption) (*GetDistrictByIDResponse, error) {
	out := new(GetDistrictByIDResponse)
	err := c.cc.Invoke(ctx, "/district.DistrictService/GetDistrictByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *districtServiceClient) GetDistrictsByIDs(ctx context.Context, in *GetDistrictsByIDsRequest, opts ...grpc.CallOption) (*GetDistrictsByIDsResponse, error) {
	out := new(GetDistrictsByIDsResponse)
	err := c.cc.Invoke(ctx, "/district.DistrictService/GetDistrictsByIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *districtServiceClient) InsertDistrict(ctx context.Context, in *InsertDistrictRequest, opts ...grpc.CallOption) (*InsertDistrictResponse, error) {
	out := new(InsertDistrictResponse)
	err := c.cc.Invoke(ctx, "/district.DistrictService/InsertDistrict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *districtServiceClient) InsertDistricts(ctx context.Context, in *InsertDistrictsRequest, opts ...grpc.CallOption) (*InsertDistrictsResponse, error) {
	out := new(InsertDistrictsResponse)
	err := c.cc.Invoke(ctx, "/district.DistrictService/InsertDistricts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *districtServiceClient) UpdateDistrict(ctx context.Context, in *UpdateDistrictRequest, opts ...grpc.CallOption) (*UpdateDistrictResponse, error) {
	out := new(UpdateDistrictResponse)
	err := c.cc.Invoke(ctx, "/district.DistrictService/UpdateDistrict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *districtServiceClient) UpdateDistricts(ctx context.Context, in *UpdateDistrictsRequest, opts ...grpc.CallOption) (*UpdateDistrictsResponse, error) {
	out := new(UpdateDistrictsResponse)
	err := c.cc.Invoke(ctx, "/district.DistrictService/UpdateDistricts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *districtServiceClient) DeleteDistrict(ctx context.Context, in *DeleteDistrictRequest, opts ...grpc.CallOption) (*DeleteDistrictResponse, error) {
	out := new(DeleteDistrictResponse)
	err := c.cc.Invoke(ctx, "/district.DistrictService/DeleteDistrict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *districtServiceClient) DeleteDistricts(ctx context.Context, in *DeleteDistrictsRequest, opts ...grpc.CallOption) (*DeleteDistrictsResponse, error) {
	out := new(DeleteDistrictsResponse)
	err := c.cc.Invoke(ctx, "/district.DistrictService/DeleteDistricts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistrictServiceServer is the server API for DistrictService service.
type DistrictServiceServer interface {
	GetAllDistricts(context.Context, *emptypb.Empty) (*GetAllDistrictsResponse, error)
	GetDistrictByID(context.Context, *GetDistrictByIDRequest) (*GetDistrictByIDResponse, error)
	GetDistrictsByIDs(context.Context, *GetDistrictsByIDsRequest) (*GetDistrictsByIDsResponse, error)
	InsertDistrict(context.Context, *InsertDistrictRequest) (*InsertDistrictResponse, error)
	InsertDistricts(context.Context, *InsertDistrictsRequest) (*InsertDistrictsResponse, error)
	UpdateDistrict(context.Context, *UpdateDistrictRequest) (*UpdateDistrictResponse, error)
	UpdateDistricts(context.Context, *UpdateDistrictsRequest) (*UpdateDistrictsResponse, error)
	DeleteDistrict(context.Context, *DeleteDistrictRequest) (*DeleteDistrictResponse, error)
	DeleteDistricts(context.Context, *DeleteDistrictsRequest) (*DeleteDistrictsResponse, error)
}

// UnimplementedDistrictServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDistrictServiceServer struct {
}

func (*UnimplementedDistrictServiceServer) GetAllDistricts(context.Context, *emptypb.Empty) (*GetAllDistrictsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllDistricts not implemented")
}
func (*UnimplementedDistrictServiceServer) GetDistrictByID(context.Context, *GetDistrictByIDRequest) (*GetDistrictByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDistrictByID not implemented")
}
func (*UnimplementedDistrictServiceServer) GetDistrictsByIDs(context.Context, *GetDistrictsByIDsRequest) (*GetDistrictsByIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDistrictsByIDs not implemented")
}
func (*UnimplementedDistrictServiceServer) InsertDistrict(context.Context, *InsertDistrictRequest) (*InsertDistrictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertDistrict not implemented")
}
func (*UnimplementedDistrictServiceServer) InsertDistricts(context.Context, *InsertDistrictsRequest) (*InsertDistrictsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertDistricts not implemented")
}
func (*UnimplementedDistrictServiceServer) UpdateDistrict(context.Context, *UpdateDistrictRequest) (*UpdateDistrictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDistrict not implemented")
}
func (*UnimplementedDistrictServiceServer) UpdateDistricts(context.Context, *UpdateDistrictsRequest) (*UpdateDistrictsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDistricts not implemented")
}
func (*UnimplementedDistrictServiceServer) DeleteDistrict(context.Context, *DeleteDistrictRequest) (*DeleteDistrictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDistrict not implemented")
}
func (*UnimplementedDistrictServiceServer) DeleteDistricts(context.Context, *DeleteDistrictsRequest) (*DeleteDistrictsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDistricts not implemented")
}

func RegisterDistrictServiceServer(s *grpc.Server, srv DistrictServiceServer) {
	s.RegisterService(&_DistrictService_serviceDesc, srv)
}

func _DistrictService_GetAllDistricts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).GetAllDistricts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/district.DistrictService/GetAllDistricts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).GetAllDistricts(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistrictService_GetDistrictByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDistrictByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).GetDistrictByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/district.DistrictService/GetDistrictByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).GetDistrictByID(ctx, req.(*GetDistrictByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistrictService_GetDistrictsByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDistrictsByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).GetDistrictsByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/district.DistrictService/GetDistrictsByIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).GetDistrictsByIDs(ctx, req.(*GetDistrictsByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistrictService_InsertDistrict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertDistrictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).InsertDistrict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/district.DistrictService/InsertDistrict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).InsertDistrict(ctx, req.(*InsertDistrictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistrictService_InsertDistricts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertDistrictsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).InsertDistricts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/district.DistrictService/InsertDistricts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).InsertDistricts(ctx, req.(*InsertDistrictsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistrictService_UpdateDistrict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDistrictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).UpdateDistrict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/district.DistrictService/UpdateDistrict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).UpdateDistrict(ctx, req.(*UpdateDistrictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistrictService_UpdateDistricts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDistrictsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).UpdateDistricts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/district.DistrictService/UpdateDistricts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).UpdateDistricts(ctx, req.(*UpdateDistrictsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistrictService_DeleteDistrict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDistrictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).DeleteDistrict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/district.DistrictService/DeleteDistrict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).DeleteDistrict(ctx, req.(*DeleteDistrictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistrictService_DeleteDistricts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDistrictsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistrictServiceServer).DeleteDistricts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/district.DistrictService/DeleteDistricts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistrictServiceServer).DeleteDistricts(ctx, req.(*DeleteDistrictsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DistrictService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "district.DistrictService",
	HandlerType: (*DistrictServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllDistricts",
			Handler:    _DistrictService_GetAllDistricts_Handler,
		},
		{
			MethodName: "GetDistrictByID",
			Handler:    _DistrictService_GetDistrictByID_Handler,
		},
		{
			MethodName: "GetDistrictsByIDs",
			Handler:    _DistrictService_GetDistrictsByIDs_Handler,
		},
		{
			MethodName: "InsertDistrict",
			Handler:    _DistrictService_InsertDistrict_Handler,
		},
		{
			MethodName: "InsertDistricts",
			Handler:    _DistrictService_InsertDistricts_Handler,
		},
		{
			MethodName: "UpdateDistrict",
			Handler:    _DistrictService_UpdateDistrict_Handler,
		},
		{
			MethodName: "UpdateDistricts",
			Handler:    _DistrictService_UpdateDistricts_Handler,
		},
		{
			MethodName: "DeleteDistrict",
			Handler:    _DistrictService_DeleteDistrict_Handler,
		},
		{
			MethodName: "DeleteDistricts",
			Handler:    _DistrictService_DeleteDistricts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "district.proto",
}
