// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: city.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetAllCities
type GetAllCitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   []*CityData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAllCitiesResponse) Reset() {
	*x = GetAllCitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllCitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCitiesResponse) ProtoMessage() {}

func (x *GetAllCitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCitiesResponse.ProtoReflect.Descriptor instead.
func (*GetAllCitiesResponse) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllCitiesResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetAllCitiesResponse) GetData() []*CityData {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetCityByID
type GetCityByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *GetCityByIDInput `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *GetCityByIDRequest) Reset() {
	*x = GetCityByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCityByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCityByIDRequest) ProtoMessage() {}

func (x *GetCityByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCityByIDRequest.ProtoReflect.Descriptor instead.
func (*GetCityByIDRequest) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{1}
}

func (x *GetCityByIDRequest) GetRequest() *GetCityByIDInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type GetCityByIDInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCityByIDInput) Reset() {
	*x = GetCityByIDInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCityByIDInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCityByIDInput) ProtoMessage() {}

func (x *GetCityByIDInput) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCityByIDInput.ProtoReflect.Descriptor instead.
func (*GetCityByIDInput) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{2}
}

func (x *GetCityByIDInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCityByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   *CityData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetCityByIDResponse) Reset() {
	*x = GetCityByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCityByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCityByIDResponse) ProtoMessage() {}

func (x *GetCityByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCityByIDResponse.ProtoReflect.Descriptor instead.
func (*GetCityByIDResponse) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{3}
}

func (x *GetCityByIDResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetCityByIDResponse) GetData() *CityData {
	if x != nil {
		return x.Data
	}
	return nil
}

// GetCitiesByIDs
type GetCitiesByIDsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *GetCitiesByIDsInput `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *GetCitiesByIDsRequest) Reset() {
	*x = GetCitiesByIDsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCitiesByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCitiesByIDsRequest) ProtoMessage() {}

func (x *GetCitiesByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCitiesByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetCitiesByIDsRequest) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{4}
}

func (x *GetCitiesByIDsRequest) GetRequest() *GetCitiesByIDsInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type GetCitiesByIDsInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCitiesByIDsInput) Reset() {
	*x = GetCitiesByIDsInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCitiesByIDsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCitiesByIDsInput) ProtoMessage() {}

func (x *GetCitiesByIDsInput) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCitiesByIDsInput.ProtoReflect.Descriptor instead.
func (*GetCitiesByIDsInput) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{5}
}

func (x *GetCitiesByIDsInput) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetCitiesByIDsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   []*CityData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetCitiesByIDsResponse) Reset() {
	*x = GetCitiesByIDsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCitiesByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCitiesByIDsResponse) ProtoMessage() {}

func (x *GetCitiesByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCitiesByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetCitiesByIDsResponse) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{6}
}

func (x *GetCitiesByIDsResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetCitiesByIDsResponse) GetData() []*CityData {
	if x != nil {
		return x.Data
	}
	return nil
}

// InsertCity
type InsertCityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *InsertCityInput `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *InsertCityRequest) Reset() {
	*x = InsertCityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertCityRequest) ProtoMessage() {}

func (x *InsertCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertCityRequest.ProtoReflect.Descriptor instead.
func (*InsertCityRequest) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{7}
}

func (x *InsertCityRequest) GetRequest() *InsertCityInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type InsertCityInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityID     string `protobuf:"bytes,1,opt,name=cityID,proto3" json:"cityID,omitempty"`
	CityName   string `protobuf:"bytes,2,opt,name=cityName,proto3" json:"cityName,omitempty"`
	CityType   string `protobuf:"bytes,3,opt,name=cityType,proto3" json:"cityType,omitempty"`
	ProvinceID string `protobuf:"bytes,4,opt,name=provinceID,proto3" json:"provinceID,omitempty"`
}

func (x *InsertCityInput) Reset() {
	*x = InsertCityInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertCityInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertCityInput) ProtoMessage() {}

func (x *InsertCityInput) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertCityInput.ProtoReflect.Descriptor instead.
func (*InsertCityInput) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{8}
}

func (x *InsertCityInput) GetCityID() string {
	if x != nil {
		return x.CityID
	}
	return ""
}

func (x *InsertCityInput) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *InsertCityInput) GetCityType() string {
	if x != nil {
		return x.CityType
	}
	return ""
}

func (x *InsertCityInput) GetProvinceID() string {
	if x != nil {
		return x.ProvinceID
	}
	return ""
}

type InsertCityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   *CityData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *InsertCityResponse) Reset() {
	*x = InsertCityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertCityResponse) ProtoMessage() {}

func (x *InsertCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertCityResponse.ProtoReflect.Descriptor instead.
func (*InsertCityResponse) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{9}
}

func (x *InsertCityResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *InsertCityResponse) GetData() *CityData {
	if x != nil {
		return x.Data
	}
	return nil
}

// InsertCities
type InsertCitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request []*InsertCityInput `protobuf:"bytes,1,rep,name=request,proto3" json:"request,omitempty"`
}

func (x *InsertCitiesRequest) Reset() {
	*x = InsertCitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertCitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertCitiesRequest) ProtoMessage() {}

func (x *InsertCitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertCitiesRequest.ProtoReflect.Descriptor instead.
func (*InsertCitiesRequest) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{10}
}

func (x *InsertCitiesRequest) GetRequest() []*InsertCityInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type InsertCitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   []*CityData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *InsertCitiesResponse) Reset() {
	*x = InsertCitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertCitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertCitiesResponse) ProtoMessage() {}

func (x *InsertCitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertCitiesResponse.ProtoReflect.Descriptor instead.
func (*InsertCitiesResponse) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{11}
}

func (x *InsertCitiesResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *InsertCitiesResponse) GetData() []*CityData {
	if x != nil {
		return x.Data
	}
	return nil
}

// UpdateCity
type UpdateCityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *UpdateCityInput `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *UpdateCityRequest) Reset() {
	*x = UpdateCityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCityRequest) ProtoMessage() {}

func (x *UpdateCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCityRequest.ProtoReflect.Descriptor instead.
func (*UpdateCityRequest) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateCityRequest) GetRequest() *UpdateCityInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type UpdateCityInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityID     string          `protobuf:"bytes,1,opt,name=cityID,proto3" json:"cityID,omitempty"`
	CityName   *OptionalString `protobuf:"bytes,2,opt,name=cityName,proto3" json:"cityName,omitempty"`
	CityType   *OptionalString `protobuf:"bytes,3,opt,name=cityType,proto3" json:"cityType,omitempty"`
	ProvinceID *OptionalString `protobuf:"bytes,4,opt,name=provinceID,proto3" json:"provinceID,omitempty"`
}

func (x *UpdateCityInput) Reset() {
	*x = UpdateCityInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCityInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCityInput) ProtoMessage() {}

func (x *UpdateCityInput) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCityInput.ProtoReflect.Descriptor instead.
func (*UpdateCityInput) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateCityInput) GetCityID() string {
	if x != nil {
		return x.CityID
	}
	return ""
}

func (x *UpdateCityInput) GetCityName() *OptionalString {
	if x != nil {
		return x.CityName
	}
	return nil
}

func (x *UpdateCityInput) GetCityType() *OptionalString {
	if x != nil {
		return x.CityType
	}
	return nil
}

func (x *UpdateCityInput) GetProvinceID() *OptionalString {
	if x != nil {
		return x.ProvinceID
	}
	return nil
}

type UpdateCityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   *CityData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateCityResponse) Reset() {
	*x = UpdateCityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCityResponse) ProtoMessage() {}

func (x *UpdateCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCityResponse.ProtoReflect.Descriptor instead.
func (*UpdateCityResponse) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateCityResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UpdateCityResponse) GetData() *CityData {
	if x != nil {
		return x.Data
	}
	return nil
}

// UpdateCities
type UpdateCitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request []*UpdateCityInput `protobuf:"bytes,1,rep,name=request,proto3" json:"request,omitempty"`
}

func (x *UpdateCitiesRequest) Reset() {
	*x = UpdateCitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCitiesRequest) ProtoMessage() {}

func (x *UpdateCitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCitiesRequest.ProtoReflect.Descriptor instead.
func (*UpdateCitiesRequest) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateCitiesRequest) GetRequest() []*UpdateCityInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type UpdateCitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   []*CityData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateCitiesResponse) Reset() {
	*x = UpdateCitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCitiesResponse) ProtoMessage() {}

func (x *UpdateCitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCitiesResponse.ProtoReflect.Descriptor instead.
func (*UpdateCitiesResponse) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateCitiesResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *UpdateCitiesResponse) GetData() []*CityData {
	if x != nil {
		return x.Data
	}
	return nil
}

// DeleteCity
type DeleteCityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *DeleteCityInput `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *DeleteCityRequest) Reset() {
	*x = DeleteCityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCityRequest) ProtoMessage() {}

func (x *DeleteCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCityRequest.ProtoReflect.Descriptor instead.
func (*DeleteCityRequest) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteCityRequest) GetRequest() *DeleteCityInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type DeleteCityInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteCityInput) Reset() {
	*x = DeleteCityInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCityInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCityInput) ProtoMessage() {}

func (x *DeleteCityInput) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCityInput.ProtoReflect.Descriptor instead.
func (*DeleteCityInput) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteCityInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   *CityData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DeleteCityResponse) Reset() {
	*x = DeleteCityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCityResponse) ProtoMessage() {}

func (x *DeleteCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCityResponse.ProtoReflect.Descriptor instead.
func (*DeleteCityResponse) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteCityResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeleteCityResponse) GetData() *CityData {
	if x != nil {
		return x.Data
	}
	return nil
}

// DeleteCities
type DeleteCitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *DeleteCitiesInput `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *DeleteCitiesRequest) Reset() {
	*x = DeleteCitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCitiesRequest) ProtoMessage() {}

func (x *DeleteCitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCitiesRequest.ProtoReflect.Descriptor instead.
func (*DeleteCitiesRequest) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteCitiesRequest) GetRequest() *DeleteCitiesInput {
	if x != nil {
		return x.Request
	}
	return nil
}

type DeleteCitiesInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []string `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteCitiesInput) Reset() {
	*x = DeleteCitiesInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCitiesInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCitiesInput) ProtoMessage() {}

func (x *DeleteCitiesInput) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCitiesInput.ProtoReflect.Descriptor instead.
func (*DeleteCitiesInput) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteCitiesInput) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeleteCitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data   []*CityData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *DeleteCitiesResponse) Reset() {
	*x = DeleteCitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCitiesResponse) ProtoMessage() {}

func (x *DeleteCitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCitiesResponse.ProtoReflect.Descriptor instead.
func (*DeleteCitiesResponse) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteCitiesResponse) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeleteCitiesResponse) GetData() []*CityData {
	if x != nil {
		return x.Data
	}
	return nil
}

// Base Data
type CityData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityID     string `protobuf:"bytes,1,opt,name=cityID,proto3" json:"cityID,omitempty"`
	CityName   string `protobuf:"bytes,2,opt,name=cityName,proto3" json:"cityName,omitempty"`
	CityType   string `protobuf:"bytes,3,opt,name=cityType,proto3" json:"cityType,omitempty"`
	ProvinceID string `protobuf:"bytes,4,opt,name=provinceID,proto3" json:"provinceID,omitempty"`
}

func (x *CityData) Reset() {
	*x = CityData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityData) ProtoMessage() {}

func (x *CityData) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityData.ProtoReflect.Descriptor instead.
func (*CityData) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{23}
}

func (x *CityData) GetCityID() string {
	if x != nil {
		return x.CityID
	}
	return ""
}

func (x *CityData) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *CityData) GetCityType() string {
	if x != nil {
		return x.CityType
	}
	return ""
}

func (x *CityData) GetProvinceID() string {
	if x != nil {
		return x.ProvinceID
	}
	return ""
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message []string `protobuf:"bytes,2,rep,name=message,proto3" json:"message,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{24}
}

func (x *Header) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Header) GetMessage() []string {
	if x != nil {
		return x.Message
	}
	return nil
}

type OptionalString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value  string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	HasSet bool   `protobuf:"varint,2,opt,name=hasSet,proto3" json:"hasSet,omitempty"`
}

func (x *OptionalString) Reset() {
	*x = OptionalString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_city_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionalString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalString) ProtoMessage() {}

func (x *OptionalString) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalString.ProtoReflect.Descriptor instead.
func (*OptionalString) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{25}
}

func (x *OptionalString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OptionalString) GetHasSet() bool {
	if x != nil {
		return x.HasSet
	}
	return false
}

var File_city_proto protoreflect.FileDescriptor

var file_city_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x69,
	0x74, 0x79, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x60, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x22, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x69,
	0x74, 0x79, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x46, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x79, 0x42, 0x79, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x79, 0x42, 0x79, 0x49, 0x44, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x43, 0x69, 0x74, 0x79, 0x42, 0x79, 0x49, 0x44, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5f, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x79, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e,
	0x43, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4c,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x25, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x62, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x42, 0x79, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x63, 0x69, 0x74, 0x79, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x44, 0x0a, 0x11, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x63, 0x69, 0x74, 0x79, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x69, 0x74, 0x79, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x81, 0x01,
	0x0a, 0x0f, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x69, 0x74,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x74,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x49,
	0x44, 0x22, 0x5e, 0x0a, 0x12, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x22, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x69,
	0x74, 0x79, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x46, 0x0a, 0x13, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x69, 0x74, 0x79,
	0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x60, 0x0a, 0x14, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x24, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x69, 0x74,
	0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x44, 0x0a, 0x11, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2f, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x69, 0x74, 0x79, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0xc3, 0x01, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x69, 0x74, 0x79,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12, 0x30, 0x0a,
	0x08, 0x63, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x63, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x30, 0x0a, 0x08, 0x63, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x63, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x34, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x0a, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x22, 0x5e, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x63, 0x69, 0x74, 0x79, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x46, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f,
	0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x69, 0x74,
	0x79, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x60, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x22, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x69,
	0x74, 0x79, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x44, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x21, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5e, 0x0a, 0x12, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x24, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x69, 0x74, 0x79,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x48, 0x0a, 0x13, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x31, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x60, 0x0a, 0x14, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x24, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x69, 0x74,
	0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x7a, 0x0a, 0x08, 0x43,
	0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x22, 0x3a, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x3e, 0x0a, 0x0e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x61, 0x73, 0x53, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x68, 0x61, 0x73,
	0x53, 0x65, 0x74, 0x32, 0x8c, 0x05, 0x0a, 0x0b, 0x43, 0x69, 0x74, 0x79, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x69, 0x74,
	0x69, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e, 0x63, 0x69,
	0x74, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x43, 0x69, 0x74, 0x79, 0x42, 0x79, 0x49, 0x44, 0x12, 0x18, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x79, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x69, 0x74,
	0x79, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x42, 0x79, 0x49, 0x44,
	0x73, 0x12, 0x1b, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x42, 0x79, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x42,
	0x79, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41,
	0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x69, 0x74, 0x79, 0x12, 0x17, 0x2e, 0x63,
	0x69, 0x74, 0x79, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x47, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x12, 0x19, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63,
	0x69, 0x74, 0x79, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x12, 0x17, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a,
	0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x19, 0x2e,
	0x63, 0x69, 0x74, 0x79, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x69, 0x74, 0x79, 0x12, 0x17, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x63, 0x69, 0x74, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0c, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x19, 0x2e, 0x63, 0x69, 0x74, 0x79,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x03, 0x5a, 0x01, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_city_proto_rawDescOnce sync.Once
	file_city_proto_rawDescData = file_city_proto_rawDesc
)

func file_city_proto_rawDescGZIP() []byte {
	file_city_proto_rawDescOnce.Do(func() {
		file_city_proto_rawDescData = protoimpl.X.CompressGZIP(file_city_proto_rawDescData)
	})
	return file_city_proto_rawDescData
}

var file_city_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_city_proto_goTypes = []interface{}{
	(*GetAllCitiesResponse)(nil),   // 0: city.GetAllCitiesResponse
	(*GetCityByIDRequest)(nil),     // 1: city.GetCityByIDRequest
	(*GetCityByIDInput)(nil),       // 2: city.GetCityByIDInput
	(*GetCityByIDResponse)(nil),    // 3: city.GetCityByIDResponse
	(*GetCitiesByIDsRequest)(nil),  // 4: city.GetCitiesByIDsRequest
	(*GetCitiesByIDsInput)(nil),    // 5: city.GetCitiesByIDsInput
	(*GetCitiesByIDsResponse)(nil), // 6: city.GetCitiesByIDsResponse
	(*InsertCityRequest)(nil),      // 7: city.InsertCityRequest
	(*InsertCityInput)(nil),        // 8: city.InsertCityInput
	(*InsertCityResponse)(nil),     // 9: city.InsertCityResponse
	(*InsertCitiesRequest)(nil),    // 10: city.InsertCitiesRequest
	(*InsertCitiesResponse)(nil),   // 11: city.InsertCitiesResponse
	(*UpdateCityRequest)(nil),      // 12: city.UpdateCityRequest
	(*UpdateCityInput)(nil),        // 13: city.UpdateCityInput
	(*UpdateCityResponse)(nil),     // 14: city.UpdateCityResponse
	(*UpdateCitiesRequest)(nil),    // 15: city.UpdateCitiesRequest
	(*UpdateCitiesResponse)(nil),   // 16: city.UpdateCitiesResponse
	(*DeleteCityRequest)(nil),      // 17: city.DeleteCityRequest
	(*DeleteCityInput)(nil),        // 18: city.DeleteCityInput
	(*DeleteCityResponse)(nil),     // 19: city.DeleteCityResponse
	(*DeleteCitiesRequest)(nil),    // 20: city.DeleteCitiesRequest
	(*DeleteCitiesInput)(nil),      // 21: city.DeleteCitiesInput
	(*DeleteCitiesResponse)(nil),   // 22: city.DeleteCitiesResponse
	(*CityData)(nil),               // 23: city.CityData
	(*Header)(nil),                 // 24: city.Header
	(*OptionalString)(nil),         // 25: city.OptionalString
	(*emptypb.Empty)(nil),          // 26: google.protobuf.Empty
}
var file_city_proto_depIdxs = []int32{
	24, // 0: city.GetAllCitiesResponse.header:type_name -> city.Header
	23, // 1: city.GetAllCitiesResponse.data:type_name -> city.CityData
	2,  // 2: city.GetCityByIDRequest.request:type_name -> city.GetCityByIDInput
	24, // 3: city.GetCityByIDResponse.header:type_name -> city.Header
	23, // 4: city.GetCityByIDResponse.data:type_name -> city.CityData
	5,  // 5: city.GetCitiesByIDsRequest.request:type_name -> city.GetCitiesByIDsInput
	24, // 6: city.GetCitiesByIDsResponse.header:type_name -> city.Header
	23, // 7: city.GetCitiesByIDsResponse.data:type_name -> city.CityData
	8,  // 8: city.InsertCityRequest.request:type_name -> city.InsertCityInput
	24, // 9: city.InsertCityResponse.header:type_name -> city.Header
	23, // 10: city.InsertCityResponse.data:type_name -> city.CityData
	8,  // 11: city.InsertCitiesRequest.request:type_name -> city.InsertCityInput
	24, // 12: city.InsertCitiesResponse.header:type_name -> city.Header
	23, // 13: city.InsertCitiesResponse.data:type_name -> city.CityData
	13, // 14: city.UpdateCityRequest.request:type_name -> city.UpdateCityInput
	25, // 15: city.UpdateCityInput.cityName:type_name -> city.OptionalString
	25, // 16: city.UpdateCityInput.cityType:type_name -> city.OptionalString
	25, // 17: city.UpdateCityInput.provinceID:type_name -> city.OptionalString
	24, // 18: city.UpdateCityResponse.header:type_name -> city.Header
	23, // 19: city.UpdateCityResponse.data:type_name -> city.CityData
	13, // 20: city.UpdateCitiesRequest.request:type_name -> city.UpdateCityInput
	24, // 21: city.UpdateCitiesResponse.header:type_name -> city.Header
	23, // 22: city.UpdateCitiesResponse.data:type_name -> city.CityData
	18, // 23: city.DeleteCityRequest.request:type_name -> city.DeleteCityInput
	24, // 24: city.DeleteCityResponse.header:type_name -> city.Header
	23, // 25: city.DeleteCityResponse.data:type_name -> city.CityData
	21, // 26: city.DeleteCitiesRequest.request:type_name -> city.DeleteCitiesInput
	24, // 27: city.DeleteCitiesResponse.header:type_name -> city.Header
	23, // 28: city.DeleteCitiesResponse.data:type_name -> city.CityData
	26, // 29: city.CityService.GetAllCities:input_type -> google.protobuf.Empty
	1,  // 30: city.CityService.GetCityByID:input_type -> city.GetCityByIDRequest
	4,  // 31: city.CityService.GetCitiesByIDs:input_type -> city.GetCitiesByIDsRequest
	7,  // 32: city.CityService.InsertCity:input_type -> city.InsertCityRequest
	10, // 33: city.CityService.InsertCities:input_type -> city.InsertCitiesRequest
	12, // 34: city.CityService.UpdateCity:input_type -> city.UpdateCityRequest
	15, // 35: city.CityService.UpdateCities:input_type -> city.UpdateCitiesRequest
	17, // 36: city.CityService.DeleteCity:input_type -> city.DeleteCityRequest
	20, // 37: city.CityService.DeleteCities:input_type -> city.DeleteCitiesRequest
	0,  // 38: city.CityService.GetAllCities:output_type -> city.GetAllCitiesResponse
	3,  // 39: city.CityService.GetCityByID:output_type -> city.GetCityByIDResponse
	6,  // 40: city.CityService.GetCitiesByIDs:output_type -> city.GetCitiesByIDsResponse
	9,  // 41: city.CityService.InsertCity:output_type -> city.InsertCityResponse
	11, // 42: city.CityService.InsertCities:output_type -> city.InsertCitiesResponse
	14, // 43: city.CityService.UpdateCity:output_type -> city.UpdateCityResponse
	16, // 44: city.CityService.UpdateCities:output_type -> city.UpdateCitiesResponse
	19, // 45: city.CityService.DeleteCity:output_type -> city.DeleteCityResponse
	22, // 46: city.CityService.DeleteCities:output_type -> city.DeleteCitiesResponse
	38, // [38:47] is the sub-list for method output_type
	29, // [29:38] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_city_proto_init() }
func file_city_proto_init() {
	if File_city_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_city_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllCitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCityByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCityByIDInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCityByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCitiesByIDsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCitiesByIDsInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCitiesByIDsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertCityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertCityInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertCityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertCitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertCitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCityInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCityInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCitiesInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_city_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionalString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_city_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_city_proto_goTypes,
		DependencyIndexes: file_city_proto_depIdxs,
		MessageInfos:      file_city_proto_msgTypes,
	}.Build()
	File_city_proto = out.File
	file_city_proto_rawDesc = nil
	file_city_proto_goTypes = nil
	file_city_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CityServiceClient is the client API for CityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CityServiceClient interface {
	GetAllCities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllCitiesResponse, error)
	GetCityByID(ctx context.Context, in *GetCityByIDRequest, opts ...grpc.CallOption) (*GetCityByIDResponse, error)
	GetCitiesByIDs(ctx context.Context, in *GetCitiesByIDsRequest, opts ...grpc.CallOption) (*GetCitiesByIDsResponse, error)
	InsertCity(ctx context.Context, in *InsertCityRequest, opts ...grpc.CallOption) (*InsertCityResponse, error)
	InsertCities(ctx context.Context, in *InsertCitiesRequest, opts ...grpc.CallOption) (*InsertCitiesResponse, error)
	UpdateCity(ctx context.Context, in *UpdateCityRequest, opts ...grpc.CallOption) (*UpdateCityResponse, error)
	UpdateCities(ctx context.Context, in *UpdateCitiesRequest, opts ...grpc.CallOption) (*UpdateCitiesResponse, error)
	DeleteCity(ctx context.Context, in *DeleteCityRequest, opts ...grpc.CallOption) (*DeleteCityResponse, error)
	DeleteCities(ctx context.Context, in *DeleteCitiesRequest, opts ...grpc.CallOption) (*DeleteCitiesResponse, error)
}

type cityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCityServiceClient(cc grpc.ClientConnInterface) CityServiceClient {
	return &cityServiceClient{cc}
}

func (c *cityServiceClient) GetAllCities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllCitiesResponse, error) {
	out := new(GetAllCitiesResponse)
	err := c.cc.Invoke(ctx, "/city.CityService/GetAllCities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityServiceClient) GetCityByID(ctx context.Context, in *GetCityByIDRequest, opts ...grpc.CallOption) (*GetCityByIDResponse, error) {
	out := new(GetCityByIDResponse)
	err := c.cc.Invoke(ctx, "/city.CityService/GetCityByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityServiceClient) GetCitiesByIDs(ctx context.Context, in *GetCitiesByIDsRequest, opts ...grpc.CallOption) (*GetCitiesByIDsResponse, error) {
	out := new(GetCitiesByIDsResponse)
	err := c.cc.Invoke(ctx, "/city.CityService/GetCitiesByIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityServiceClient) InsertCity(ctx context.Context, in *InsertCityRequest, opts ...grpc.CallOption) (*InsertCityResponse, error) {
	out := new(InsertCityResponse)
	err := c.cc.Invoke(ctx, "/city.CityService/InsertCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityServiceClient) InsertCities(ctx context.Context, in *InsertCitiesRequest, opts ...grpc.CallOption) (*InsertCitiesResponse, error) {
	out := new(InsertCitiesResponse)
	err := c.cc.Invoke(ctx, "/city.CityService/InsertCities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityServiceClient) UpdateCity(ctx context.Context, in *UpdateCityRequest, opts ...grpc.CallOption) (*UpdateCityResponse, error) {
	out := new(UpdateCityResponse)
	err := c.cc.Invoke(ctx, "/city.CityService/UpdateCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityServiceClient) UpdateCities(ctx context.Context, in *UpdateCitiesRequest, opts ...grpc.CallOption) (*UpdateCitiesResponse, error) {
	out := new(UpdateCitiesResponse)
	err := c.cc.Invoke(ctx, "/city.CityService/UpdateCities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityServiceClient) DeleteCity(ctx context.Context, in *DeleteCityRequest, opts ...grpc.CallOption) (*DeleteCityResponse, error) {
	out := new(DeleteCityResponse)
	err := c.cc.Invoke(ctx, "/city.CityService/DeleteCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityServiceClient) DeleteCities(ctx context.Context, in *DeleteCitiesRequest, opts ...grpc.CallOption) (*DeleteCitiesResponse, error) {
	out := new(DeleteCitiesResponse)
	err := c.cc.Invoke(ctx, "/city.CityService/DeleteCities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CityServiceServer is the server API for CityService service.
type CityServiceServer interface {
	GetAllCities(context.Context, *emptypb.Empty) (*GetAllCitiesResponse, error)
	GetCityByID(context.Context, *GetCityByIDRequest) (*GetCityByIDResponse, error)
	GetCitiesByIDs(context.Context, *GetCitiesByIDsRequest) (*GetCitiesByIDsResponse, error)
	InsertCity(context.Context, *InsertCityRequest) (*InsertCityResponse, error)
	InsertCities(context.Context, *InsertCitiesRequest) (*InsertCitiesResponse, error)
	UpdateCity(context.Context, *UpdateCityRequest) (*UpdateCityResponse, error)
	UpdateCities(context.Context, *UpdateCitiesRequest) (*UpdateCitiesResponse, error)
	DeleteCity(context.Context, *DeleteCityRequest) (*DeleteCityResponse, error)
	DeleteCities(context.Context, *DeleteCitiesRequest) (*DeleteCitiesResponse, error)
}

// UnimplementedCityServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCityServiceServer struct {
}

func (*UnimplementedCityServiceServer) GetAllCities(context.Context, *emptypb.Empty) (*GetAllCitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCities not implemented")
}
func (*UnimplementedCityServiceServer) GetCityByID(context.Context, *GetCityByIDRequest) (*GetCityByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCityByID not implemented")
}
func (*UnimplementedCityServiceServer) GetCitiesByIDs(context.Context, *GetCitiesByIDsRequest) (*GetCitiesByIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCitiesByIDs not implemented")
}
func (*UnimplementedCityServiceServer) InsertCity(context.Context, *InsertCityRequest) (*InsertCityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertCity not implemented")
}
func (*UnimplementedCityServiceServer) InsertCities(context.Context, *InsertCitiesRequest) (*InsertCitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertCities not implemented")
}
func (*UnimplementedCityServiceServer) UpdateCity(context.Context, *UpdateCityRequest) (*UpdateCityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCity not implemented")
}
func (*UnimplementedCityServiceServer) UpdateCities(context.Context, *UpdateCitiesRequest) (*UpdateCitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCities not implemented")
}
func (*UnimplementedCityServiceServer) DeleteCity(context.Context, *DeleteCityRequest) (*DeleteCityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCity not implemented")
}
func (*UnimplementedCityServiceServer) DeleteCities(context.Context, *DeleteCitiesRequest) (*DeleteCitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCities not implemented")
}

func RegisterCityServiceServer(s *grpc.Server, srv CityServiceServer) {
	s.RegisterService(&_CityService_serviceDesc, srv)
}

func _CityService_GetAllCities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServiceServer).GetAllCities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/city.CityService/GetAllCities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServiceServer).GetAllCities(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityService_GetCityByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCityByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServiceServer).GetCityByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/city.CityService/GetCityByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServiceServer).GetCityByID(ctx, req.(*GetCityByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityService_GetCitiesByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCitiesByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServiceServer).GetCitiesByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/city.CityService/GetCitiesByIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServiceServer).GetCitiesByIDs(ctx, req.(*GetCitiesByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityService_InsertCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServiceServer).InsertCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/city.CityService/InsertCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServiceServer).InsertCity(ctx, req.(*InsertCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityService_InsertCities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertCitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServiceServer).InsertCities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/city.CityService/InsertCities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServiceServer).InsertCities(ctx, req.(*InsertCitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityService_UpdateCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServiceServer).UpdateCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/city.CityService/UpdateCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServiceServer).UpdateCity(ctx, req.(*UpdateCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityService_UpdateCities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServiceServer).UpdateCities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/city.CityService/UpdateCities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServiceServer).UpdateCities(ctx, req.(*UpdateCitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityService_DeleteCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServiceServer).DeleteCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/city.CityService/DeleteCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServiceServer).DeleteCity(ctx, req.(*DeleteCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityService_DeleteCities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityServiceServer).DeleteCities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/city.CityService/DeleteCities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityServiceServer).DeleteCities(ctx, req.(*DeleteCitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "city.CityService",
	HandlerType: (*CityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllCities",
			Handler:    _CityService_GetAllCities_Handler,
		},
		{
			MethodName: "GetCityByID",
			Handler:    _CityService_GetCityByID_Handler,
		},
		{
			MethodName: "GetCitiesByIDs",
			Handler:    _CityService_GetCitiesByIDs_Handler,
		},
		{
			MethodName: "InsertCity",
			Handler:    _CityService_InsertCity_Handler,
		},
		{
			MethodName: "InsertCities",
			Handler:    _CityService_InsertCities_Handler,
		},
		{
			MethodName: "UpdateCity",
			Handler:    _CityService_UpdateCity_Handler,
		},
		{
			MethodName: "UpdateCities",
			Handler:    _CityService_UpdateCities_Handler,
		},
		{
			MethodName: "DeleteCity",
			Handler:    _CityService_DeleteCity_Handler,
		},
		{
			MethodName: "DeleteCities",
			Handler:    _CityService_DeleteCities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "city.proto",
}
